apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nginx
name: ingress-nginx
namespace: ingress-nginx
releaseName: ingress-nginx
repo: https://kubernetes.github.io/ingress-nginx 
valuesFile: values.yaml
